axa-group/oauth2-mock-server

.eslintrc.json, .travis.yml, appveyor.yml, package-lock.json, package.json
First PR.
**TL;DR**
Woot! 😜  
**Gory details**
This adds a build file that
- Should trigger a build for every new pull request (or push to an existing pull request)
- Should trigger a build for every merge to master
- Builds will run a matrix of jobs against os/linux and node 8/10
This also shuts down a pesky eslint rule that makes little sense in a xplat project. The `.gitattributes` files ensure line endings correctness.
**BONUS PACK:** Also shuts down a npm warning about the link to the repository being missing.
=> Add Travis and AppVeyor backed continous integrations

CHANGELOG.md, README.md, lib/oauth2-service.js, test/oauth2-service.test.js
Add [Resource Owner Password Credentials grant](https://tools.ietf.org/html/rfc6749#section-4.3).
=> Add Resource Owner Password Credentials grant

CHANGELOG.md, package-lock.json, package.json
Update npm dependencies to fix CVE-2018-16469
=> Update npm dependencies to fix CVE-2018-16469

.eslintignore, .eslintrc.json, bin/oauth2-mock-server, index.js, jest.config.js, lib/http-server.js, lib/jwk-store.js, lib/oauth2-issuer.js, lib/oauth2-server.js, lib/oauth2-service.js, package-lock.json, package.json, test/cli.test.js, test/http-server.test.js, test/jwk-store.test.js, test/keys/index.js, test/lib/child-script.js, test/oauth2-issuer.test.js, test/oauth2-server.test.js, test/oauth2-service.test.js
Replaces ESLint recommended rules with Airbnb's.
=> Use Airbnb's ESLint rules

CHANGELOG.md, package-lock.json, package.json, test/jwk-store.test.js
=> Version 1.2.0

README.md
- I only made a change to README.md.
When I used your instructions (and being sort of new to JS/ Node) the code didn't work, so I noticed that the instructions had a slight syntax error, which I corrected.
=> README.md: syntax of javascript require()

lib/oauth2-service.js, test/oauth2-service.test.js
=> Changes strategy for extraction of client_id in /token endpoint

lib/oauth2-service.js, package-lock.json, package.json, test/oauth2-service.test.js
Solves #20 
Enable CORS requests in the server. 
I believe this is acceptable behaviour for a mock server.
=> Adds CORS support to the server

CHANGELOG.md, README.md, lib/oauth2-issuer.js, lib/oauth2-service.js, package-lock.json, package.json, test/oauth2-service.test.js
- Add HTTP request object to `OAuth2Service`'s events
- Add `beforeTokenSigning` event to `OAuth2Service`
=> Events enhancements

.github/dependabot.yml
Add yaml based dependabot configuration
- Scan will be triggered on a weekly basis
- Both package.json and .lock file will be updated on each detected upgrade proposal
=> Add yaml based dependabot configuration

.editorconfig, .github/workflows/main.yml, .vscode/extensions.json, .vscode/settings.json
- Make the contributing experience from VSCode a tab better
- Unify xplat CI builds through GitHub actions
=> GitHub actions FTW!

CHANGELOG.md, package.json
=> Publish v3.0.0

CHANGELOG.md, package.json
- Include missing files on pack/publish
=> Include missing files on pack/publish

CHANGELOG.md, README.md, package.json
=> Version 3.1.0

CHANGELOG.md, README.md, package.json, src/lib/http-server.ts, src/lib/oauth2-server.ts
Minor fixups following #139 merge
=> Version 4.1.0

CHANGELOG.md, package.json, yarn.lock
Version bump to release fix to #141
=> Version 4.1.1

CHANGELOG.md, package.json
Prepare release 4.3.0 including #164 from @cfman
=> Version 4.3.0

.github/workflows/code_ql.yml, src/lib/oauth2-service.ts
LGTM is sunsetting (https://github.blog/2022-08-15-the-next-step-for-lgtm-com-github-code-scanning/). Let's move over to CodeQL
=> Enable CodeQL on pull requests

CHANGELOG.md, package.json
=> Version 5.0.1

README.md
Makes https://www.npmjs.com/package/oauth2-mock-server easier to the eye ;-)
=> [README] Reduce horizontal scrolling

.github/workflows/code_ql.yml
Supercharge CodeQL analysis to the highest level (cf. [doc](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#using-queries-in-ql-packs))
=> Raise CodeQL scanning level

CHANGELOG.md, package.json
=> Version 6.0.1

.github/dependabot.yml, .github/workflows/code_ql.yml, .github/workflows/main.yml
=> Bump GitHub actions versions

.eslintrc.json, .github/workflows/main.yml, README.md, package.json, tsconfig.json, yarn.lock
=> Drop support of Node 16

CHANGELOG.md, package.json
=> Version 7.0.0

.github/workflows/clear_closed_pr_cache.yml, .github/workflows/code_ql.yml, .github/workflows/main.yml
- Prettify CodeQL workflow
- Give a meaningful name to the main workflow
- Add a workflow to clear obsolete caches
=> Minor workflow changes

CHANGELOG.md, package.json, src/lib/helpers.ts, yarn.lock
=> Version 7.1.1

.github/workflows/main.yml, package.json, yarn.lock
Add support for Node 22, as well as minor dependency upgrades
=> Node 22 support

CHANGELOG.md, package.json
Describe Your PR Here!
- Add support for Node.js 22
=> Poveden/release 7.1.2

CHANGELOG.md, package.json
Version 7.2.0
- Include scope in token for authorization_code and refresh_token grants (by [PetrasJaug](https://github.com/PetrasJaug))
- Add PKCE support (by [tanettrimas](https://github.com/tanettrimas))
- Update dependencies
=> Version 7.2.0

CHANGELOG.md, package.json
=> Version v8.0.0

.github/workflows/main.yml, CHANGELOG.md, package.json, src/index.ts, test/http-server.test.ts, test/jwk-store.test.ts, test/oauth2-issuer.test.ts, test/oauth2-server.test.ts, test/oauth2-service.test.ts
=> Export HttpServer and OAuth2Service

package.json
=> Enhance package description
